# Generated by Django 4.1.7 on 2023-03-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=8)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
