# Generated by Django 4.1.7 on 2023-03-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='log',
            name='symbol',
        ),
    ]
