# Generated by Django 4.1.7 on 2023-04-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_log_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='company',
        ),
        migrations.DeleteModel(
            name='Database',
        ),
    ]
