# Generated by Django 4.1.7 on 2023-04-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='log_db', to='home.database'),
            preserve_default=False,
        ),
    ]
