# Generated by Django 4.1.7 on 2023-04-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_dataext_rename_data_datadetails_delete_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadetails',
            name='cid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataext',
            name='cid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
